"""increse description legnth or img_link legnth

Revision ID: 9611c7c07ab1
Revises: 
Create Date: 2025-02-22 16:17:07.496143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9611c7c07ab1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Animetable', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('img_url',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=500),
               existing_nullable=False)

    with op.batch_alter_table('Mangatable', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('img_url',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Mangatable', schema=None) as batch_op:
        batch_op.alter_column('img_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    with op.batch_alter_table('Animetable', schema=None) as batch_op:
        batch_op.alter_column('img_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
